### ISSUE TITLE
Test Kitchen fails to deploy `libraries/dnf-query.py`

### ISSUE THREAD

**Issue by rhass** [pantheon-cookbooks/dnf#14]
Test kitchen appears to be omitting the python file from the libraries directory.

```
 * dnf_package[git] action install

           ================================================================================
           Error executing action `install` on resource 'dnf_package[git]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory - /tmp/kitchen/cache/cookbooks/dnf/libraries/dnf-query.py

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:112:in `available_version'
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:77:in `block in load_current_resource'
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:75:in `each'
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:75:in `load_current_resource'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/omnibus-chef-arm/recipes/git_config.rb

            20:   dnf_package 'git'
            21: else

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/omnibus-chef-arm/recipes/git_config.rb:20:in `from_file'

           dnf_package("git") do
             provider Chef::Provider::Package::Dnf
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "git"
             declared_type :dnf_package
             cookbook_name "omnibus-chef-arm"
             recipe_name "git_config"
           end


       Running handlers:
       [2016-01-28T18:21:30-05:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-01-28T18:21:30-05:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 22 seconds
       [2016-01-28T18:21:30-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-01-28T18:21:30-05:00] ERROR: dnf_package[git] (omnibus-chef-arm::git_config line 20) had an error: Errno::ENOENT: No such file or directory - /tmp/kitchen/cache/cookbooks/dnf/libraries/dnf-query.py
       [2016-01-28T18:21:32-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

While this is likely bug in test-kitchen, I tried identifying what causes the exclusion in kitchen, and haven't had much luck. I suspect it will likely be easier to resolve this issue in the cookbook instead.

**Comment by coderanger** [comment]
Related Kitchen issue: https://github.com/test-kitchen/test-kitchen/issues/929

The fact that this worked in Test Kitchen is indeed a bug.

**Comment by lamont-granquist** [comment]
should have been fixed in 12.8.1 in core: https://github.com/chef/chef/commit/b62e6ae14ddd9c60035f4ec314f4c6d0ab47777e

**Comment by VanAxe** [comment]
I'm having the same issue on Fedora 24 as well.

```plaintext
# Inside target box 

$ uname -a
Linux default-fedora-24 4.5.5-300.fc24.x86_64 #1 SMP Thu May 19 13:05:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ chef-client --version
Chef: 12.16.42

# On host

$ chef --version
Chef Development Kit Version: 0.19.6
chef-client version: ERROR
delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
berks version: 5.1.0
kitchen version: 1.13.2
```

```plaintext
           ================================================================================
           Error executing action `install` on resource 'dnf_package[/tmp/kitchen/cache/rpmfusion-free-release-24.noarch.rpm]'
           ================================================================================
           
           Errno::ENOENT
           -------------
           No such file or directory - /tmp/kitchen/cache/cookbooks/dnf/libraries/dnf-query.py
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:112:in `available_version'
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:77:in `block in load_current_resource'
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:75:in `each'
           /tmp/kitchen/cache/cookbooks/dnf/libraries/provider_dnf_package.rb:75:in `load_current_resource'
```

**Comment by VanAxe** [comment]
I tested again, upgrading my local and kitchen box chef to `12.17.15`.

I am getting the same results.

**Comment by redeemed2011** [comment]
Has anyone determined how to resolve this? The issue persists in my own efforts as well. I am using chef zero in my case.

**Comment by spheromak** [comment]
@redeemed2011 should be fixed with the latest master of chef having merged dnf support in the core.
